version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swiftcodes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/swiftcodes
    depends_on:
      - db
    command: >
      bash -c "sleep 3 &&
               python load_excel.py &&
               uvicorn main:app --host 0.0.0.0 --port 8080 --reload"

  test:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/swiftcodes
    command: ["pytest", "tests/"]

volumes:
  postgres_data:
